version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: one-time-secrets-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - secret_storage:/usr/src/app/storage
    ports:
      - "3000:3000"

volumes:
  secret_storage:
    driver: local
