version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: one-time-secrets-dev
    environment:
      - NODE_ENV=development
      - PORT=3000
      - STORAGE_DIR=/usr/src/app/storage
    volumes:
      - secret_storage:/usr/src/app/storage
      - test_storage:/usr/src/app/test-storage
      - ../src:/usr/src/app/src
      - ../public:/usr/src/app/public
      - ../tests:/usr/src/app/tests
    ports:
      - "3000:3000"
    command: npm run dev

volumes:
  secret_storage:
    driver: local
  test_storage:
    driver: local
